# Centralized Audit Action Constants
# Helps prevent hardcoded strings in the codebase.

LOGIN = "LOGIN"
LOGOUT = "LOGOUT"
REGISTER = "REGISTER"
PASSWORD_RESET = "PASSWORD_RESET"

DOCUMENT_CREATED = "DOCUMENT_CREATED"
DOCUMENT_UPDATED = "DOCUMENT_UPDATED"
DOCUMENT_DELETED = "DOCUMENT_DELETED"
DOCUMENT_VIEWED = "DOCUMENT_VIEWED"
DOCUMENT_DOWNLOADED = "DOCUMENT_DOWNLOADED"

CONTACT_CREATED = "CONTACT_CREATED"
CONTACT_UPDATED = "CONTACT_UPDATED"
CONTACT_DELETED = "CONTACT_DELETED"

DOCUMENT_SHARED = "DOCUMENT_SHARED"
SHARE_ACCEPTED = "SHARE_ACCEPTED"
SHARE_DECLINED = "SHARE_DECLINED"
SHARE_REVOKED = "SHARE_REVOKED"

NOTIFICATION_READ = "NOTIFICATION_READ"
NOTIFICATION_MARKED_ALL_READ = "NOTIFICATION_MARKED_ALL_READ"

PROFILE_UPDATED = "PROFILE_UPDATED"
PASSWORD_CHANGED = "PASSWORD_CHANGED"
SETTINGS_UPDATED = "SETTINGS_UPDATED"

SECURITY_SETTINGS_UPDATED = "SECURITY_SETTINGS_UPDATED"
NOTIFICATION_SETTINGS_UPDATED = "NOTIFICATION_SETTINGS_UPDATED"
PRIVACY_SETTINGS_UPDATED = "PRIVACY_SETTINGS_UPDATED"
REMINDER_SETTINGS_UPDATED = "REMINDER_SETTINGS_UPDATED"
ACCOUNT_SETTINGS_EXPORTED = "ACCOUNT_SETTINGS_EXPORTED"
ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
