"""create notifications table

Revision ID: 33b1f807178b
Revises: 621efbe7b172
Create Date: 2026-06-05 14:03:06.432226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b1f807178b'
down_revision: Union[str, Sequence[str], None] = '621efbe7b172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notification_type_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_document_id', sa.Uuid(), nullable=True),
    sa.Column('related_contact_id', sa.Uuid(), nullable=True),
    sa.Column('related_share_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_contact_id'], ['trusted_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_share_id'], ['document_shares.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_contact_id'), 'notifications', ['related_contact_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_document_id'), 'notifications', ['related_document_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_share_id'), 'notifications', ['related_share_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_share_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_document_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_contact_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
