"""add_sharing_fields

Revision ID: 4ecb7140bfe1
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 08:40:11.759086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecb7140bfe1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_shares', sa.Column('access_level', sa.String(length=50), nullable=True))
    op.add_column('document_shares', sa.Column('allow_download', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('document_shares', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_shares', 'password_hash')
    op.drop_column('document_shares', 'allow_download')
    op.drop_column('document_shares', 'access_level')
    # ### end Alembic commands ###
