"""add_family_relationships

Revision ID: 9897205b7f42
Revises: 4ecb7140bfe1
Create Date: 2026-06-29 07:59:50.631731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9897205b7f42'
down_revision: Union[str, Sequence[str], None] = '4ecb7140bfe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('dependent_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.Enum('PARENT', 'CHILD', 'GUARDIAN', 'DEPENDENT', 'SPOUSE', 'SIBLING', 'OTHER', name='relationship_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'REMOVED', name='relationship_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_relationships_dependent_id'), 'family_relationships', ['dependent_id'], unique=False)
    op.create_index(op.f('ix_family_relationships_guardian_id'), 'family_relationships', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_family_relationships_id'), 'family_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_family_relationships_invited_by'), 'family_relationships', ['invited_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_relationships_invited_by'), table_name='family_relationships')
    op.drop_index(op.f('ix_family_relationships_id'), table_name='family_relationships')
    op.drop_index(op.f('ix_family_relationships_guardian_id'), table_name='family_relationships')
    op.drop_index(op.f('ix_family_relationships_dependent_id'), table_name='family_relationships')
    op.drop_table('family_relationships')
    # ### end Alembic commands ###
