"""add trusted contacts table

Revision ID: cb75116bd361
Revises: 3fbdfb2d0dec
Create Date: 2026-06-05 09:40:06.926489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb75116bd361'
down_revision: Union[str, Sequence[str], None] = '3fbdfb2d0dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'email', name='uq_trusted_contacts_owner_email')
    )
    op.create_index(op.f('ix_trusted_contacts_id'), 'trusted_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_owner_id'), 'trusted_contacts', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_contacts_owner_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    # ### end Alembic commands ###
