"""add_guardian_visibility_to_documents

Revision ID: e88af3bbe42b
Revises: 9897205b7f42
Create Date: 2026-06-29 08:25:45.355691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88af3bbe42b'
down_revision: Union[str, Sequence[str], None] = '9897205b7f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('guardian_visibility', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'guardian_visibility')
    # ### end Alembic commands ###
